[package]
name = "grpc"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

[[bin]] # Bin to run the gRPC server
name = "grpc-server"
path = "src/server.rs"
doc = false

[[bin]] # Bin to run the gRPC client
name = "grpc-client"
path = "src/client.rs"
doc = false

[dependencies]
http = "0.2"
tonic = "0.5"
prost = "0.8"
tokio = { version = "1.0", features = ["full"] }
opentelemetry = { path = "../../opentelemetry" }
opentelemetry-jaeger = { path = "../../opentelemetry-jaeger" }

[build-dependencies]
tonic-build = "0.5"
