[package]
name = "tracing-http-propagator"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.75.0"
publish = false
autobenches = false

[[bin]] # Bin to run the http server
name = "http-server"
path = "src/server.rs"
doc = false
bench = false

[[bin]] # Bin to run the client
name = "http-client"
path = "src/client.rs"
doc = false
bench = false

[dependencies]
http-body-util = { workspace = true }
hyper = { workspace = true, features = ["full"] }
hyper-util = { workspace = true, features = ["full"] }
tokio = { workspace = true, features = ["full"] }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
opentelemetry-http = { workspace = true }
opentelemetry-stdout = { workspace = true, features = ["trace", "logs"] }
opentelemetry-semantic-conventions = { workspace = true }
opentelemetry-appender-log = { workspace = true }
log = { workspace = true, features = ["kv"]}
