[package]
name = "basic-otlp-http"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[features]
default = ["reqwest-blocking"]
reqwest-blocking = ["opentelemetry-otlp/reqwest-blocking-client"]

[dependencies]
once_cell = { workspace = true }
opentelemetry = { path = "../../../opentelemetry" }
opentelemetry_sdk = { path = "../../../opentelemetry-sdk" }
opentelemetry-otlp = { path = "../.."}
opentelemetry-appender-tracing = { path = "../../../opentelemetry-appender-tracing"}

tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true, features = ["std"]}
tracing-subscriber = { workspace = true, features = ["env-filter","registry", "std", "fmt"] }
