[package]
name = "basic-otlp-http"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
once_cell = { workspace = true }
opentelemetry = { path = "../../../opentelemetry" }
opentelemetry-sdk = { path = "../../../opentelemetry-sdk", features = ["rt-tokio", "metrics", "logs"] }
opentelemetry-otlp = { path = "../..", features = ["http-proto", "reqwest-client", "logs"] }
opentelemetry-appender-tracing = { path = "../../../opentelemetry-appender-tracing", default-features = false}
opentelemetry-semantic-conventions = { path = "../../../opentelemetry-semantic-conventions" }

tokio = { workspace = true, features = ["full"] }
opentelemetry-appender-log = { path = "../../../opentelemetry-appender-log", default-features = false}
log = { workspace = true }
