[package]
name = "basic-otlp-http"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
once_cell = "1.17"
opentelemetry = { path = "../../../opentelemetry" }
opentelemetry_sdk = { path = "../../../opentelemetry-sdk", features = ["rt-tokio", "metrics", "logs", "logs_level_enabled"] }
opentelemetry-otlp = { path = "../..", features = ["http-proto", "reqwest-client", "logs"] }
opentelemetry-appender-tracing = { path = "../../../opentelemetry-appender-tracing"}
opentelemetry-semantic-conventions = { path = "../../../opentelemetry-semantic-conventions" }

tokio = { version = "1.0", features = ["full"] }
tracing-subscriber = { version = "0.3.0", default-features = false, features = ["registry", "std"] }
tracing = { version = "0.1.37", default-features = false, features = ["std"] }
tracing-core = "0.1.31"
