[package]
name = "basic-otlp-http"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.75.0"
publish = false
autobenches = false

[[bin]]
name = "basic-otlp-http"
path = "src/main.rs"
bench = false

[features]
default = ["reqwest-blocking"]
reqwest-blocking = ["opentelemetry-otlp/reqwest-blocking-client"]
gzip = ["opentelemetry-otlp/gzip-http"]
zstd = ["opentelemetry-otlp/zstd-http"]

[dependencies]
opentelemetry = { path = "../../../opentelemetry" }
opentelemetry_sdk = { path = "../../../opentelemetry-sdk" }
opentelemetry-otlp = { workspace = true }
opentelemetry-appender-tracing = { workspace = true }

tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true, features = ["std"]}
tracing-subscriber = { workspace = true, features = ["env-filter","registry", "std", "fmt"] }

[lints]
workspace = true
