language: rust
rust:
 - stable
cache: cargo

before_install:
  - sudo apt-get -y install unzip gcc
  - curl -L -O https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protoc-3.11.4-linux-x86_64.zip
  - unzip protoc-3.11.4-linux-x86_64.zip -d protoc
  - sudo cp protoc/bin/protoc /usr/bin/protoc
  - sudo cp -r protoc/include/* /usr/include/
  - rustup component add rustfmt

script:
  - cargo build --verbose
  - cargo doc --verbose

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master 
  local_dir: target/doc/
