[package]
name = "logs-basic"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.75.0"
publish = false
autobenches = false

[[bin]]
name = "logs-basic"
path = "src/main.rs"
bench = false

[dependencies]
opentelemetry_sdk = { workspace = true, features = ["logs"] }
opentelemetry-stdout = { workspace = true, features = ["logs"] }
opentelemetry-appender-log = { workspace = true }
log = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["full"] }
