[package]
name = "actix-udp-example"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
opentelemetry = { path = "../../../opentelemetry" }
opentelemetry-jaeger = { path = "../.." }
actix-web = "4.1"
actix-service = "2"
env_logger = "0.9"
