[package]
name = "datadog"
version = "0.1.0"
edition = "2018"

[dependencies]
opentelemetry = { path = "../../opentelemetry" }
opentelemetry-contrib = { path = "../../opentelemetry-contrib", features = ["datadog"] }
