[package]
name = "datadog"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

[dependencies]
opentelemetry = { path = "../../opentelemetry" }
opentelemetry-datadog = { path = "../../opentelemetry-datadog", features = ["reqwest-blocking-client"] }
