[package]
name = "zpages"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opentelemetry = { path = "../../opentelemetry", features = ["rt-tokio"] }
opentelemetry-zpages = { path = "../../opentelemetry-zpages" }
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1.0", features = ["full"] }
rand = "0.8"