[package]
name = "basic-otlp"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.75.0"
publish = false
autobenches = false

[[bin]]
name = "basic-otlp"
path = "src/main.rs"
bench = false

[dependencies]
opentelemetry = { workspace = true, features = ["trace", "metrics", "logs"] }
opentelemetry_sdk = { workspace = true, features = ["trace", "metrics", "logs"] }
opentelemetry-otlp = { workspace = true, features = ["grpc-tonic", "trace", "metrics", "logs", "internal-logs"] }
opentelemetry-appender-log = { workspace = true }

log = { workspace = true, features = ["kv"] }
tokio = { workspace = true, features = ["full"] }

[lints]
workspace = true
