[package]
name = "basic-otlp"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
once_cell = "1.17"
opentelemetry_api = { path = "../../../opentelemetry-api", features = ["metrics", "logs"] }
opentelemetry_sdk = { path = "../../../opentelemetry-sdk", features = ["rt-tokio", "logs"] }
opentelemetry-otlp = { path = "../../../opentelemetry-otlp", features = ["tonic", "metrics", "logs"] }
opentelemetry-semantic-conventions = { path = "../../../opentelemetry-semantic-conventions" }
tokio = { version = "1.0", features = ["full"] }
opentelemetry-appender-log = { path = "../../../opentelemetry-appender-log"}
log = {version = "0.4.17"}