[package]
name = "dynatrace"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
futures = "0.3"
http = "0.2"
lazy_static = "1.4"
opentelemetry = { path = "../../opentelemetry", default-features = false, features = ["trace"] }
opentelemetry-dynatrace = { path = "../../opentelemetry-dynatrace" }
opentelemetry-http = { version = "0.8", default-features = false }
opentelemetry-otlp = { version = "0.12", default-features = false, features = ["http-proto", "reqwest-client"] }
opentelemetry-semantic-conventions = "0.11"
tokio = { version = "1.0", features = ["full"] }
