[package]
name = "async"
version = "0.1.0"
edition = "2018"

[dependencies]
futures = "0.3"
thrift = "0.13"
tokio = { version = "1.0", features = ["full"] }
opentelemetry = { path = "../../opentelemetry", features = ["rt-tokio"] }
opentelemetry-jaeger = { path = "../../opentelemetry-jaeger", features = ["tokio"] }
