[package]
name = "aws-xray"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]] # Bin to run the http server
name = "http-server"
path = "src/server.rs"

[[bin]] # Bin to run the client
name = "http-client"
path = "src/client.rs"

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1.0", features = ["full"] }
opentelemetry = { path = "../../opentelemetry", features = ["http"] }
opentelemetry-contrib = { path = "../../opentelemetry-contrib", features = ["aws-xray"] }
