[package]
name = "multiple-span-processors"
version = "0.1.0"
edition = "2018"

[dependencies]
opentelemetry = { path = "../../opentelemetry", features = ["rt-tokio"] }
opentelemetry-zipkin = { path = "../../opentelemetry-zipkin", default-features=false, features=["reqwest-client"]}
opentelemetry-jaeger = { path = "../../opentelemetry-jaeger", features = ["tokio"] }
tokio = { version = "1.0", features = ["full"] }
