[package]
name = "actix-udp-example"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
opentelemetry = { path = "../../opentelemetry" }
opentelemetry-jaeger = { path = "../../opentelemetry-jaeger" }
thrift = "0.13"
futures = "0.3"
actix-web = "3"
actix-service = "1"
env_logger = "0.8.2"
