[package]
name = "actix-udp-example"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
opentelemetry = { path = "../../opentelemetry" }
opentelemetry-jaeger = { path = "../../opentelemetry-jaeger" }
actix-web = "4.1"
actix-service = "2"
env_logger = "0.9"
