[package]
name = "actix-http-example"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

[dependencies]
opentelemetry = { path = "../../opentelemetry", features = ["rt-tokio"] }
opentelemetry-jaeger = { path = "../../opentelemetry-jaeger", features = ["reqwest_collector_client", "tokio"] }
thrift = "0.13"
futures = "0.3"
actix-web = "4.0.0-beta.4"
actix-service = "2.0.0-beta.5"
env_logger = "0.8.2"
tokio = { version = "1", features = ["full"] }
