[package]
name = "actix-http-example"
version = "0.1.0"
edition = "2018"

[dependencies]
opentelemetry = { path = "../../opentelemetry", features = ["tokio"] }
opentelemetry-jaeger = { path = "../../opentelemetry-jaeger", features = ["collector_client", "tokio"] }
thrift = "0.13"
futures = "0.3"
actix-web = "3"
actix-service = "1"
env_logger = "0.7.1"
tokio = { version = "0.2.21", features = ["full"] }
