[package]
name = "actix-http-example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
opentelemetry = { path = "../../opentelemetry", features = ["rt-tokio"] }
opentelemetry_sdk = { path = "../../opentelemetry-sdk", features = ["rt-tokio-current-thread"]}
opentelemetry-otlp = { path = "../../opentelemetry-otlp" }
actix-web = "4.1.0"
actix-service = "2.0.0"
env_logger = "0.9.0"
tokio = { version = "1", features = ["full"] }
