[package]
name = "actix-http-example"
version = "0.1.0"
edition = "2018"

[dependencies]
opentelemetry = { path = "../../opentelemetry", features = ["tokio-support"] }
opentelemetry-jaeger = { path = "../../opentelemetry-jaeger", features = ["reqwest_collector_client", "tokio"] }
thrift = "0.13"
futures = "0.3"
actix-web = "3"
actix-service = "1"
env_logger = "0.8.2"
tokio = { version = "1.0", features = ["full"] }
