[package]
name = "opentelemetry-zipkin"
version = "0.3.0"
authors = ["OpenTelemetry Authors <cncf-opentelemetry-contributors@lists.cncf.io>"]
description = "Zipkin exporter for OpenTelemetry"
homepage = "https://github.com/open-telemetry/opentelemetry-rust"
repository = "https://github.com/open-telemetry/opentelemetry-rust"
readme = "README.md"
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
    "asynchronous",
]
keywords = ["opentelemetry", "zipkin", "tracing", "async"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
opentelemetry = { version = "0.7.0", path = ".." }
reqwest = { version = "0.10.4", features = ["blocking"] }
serde_json = "1.0"
serde = { version = "1.0.104", features = ["derive"] }
typed-builder = "0.5.1"
