[package]
name = "opentelemetry-zipkin"
version = "0.7.0"
authors = ["OpenTelemetry Authors <cncf-opentelemetry-contributors@lists.cncf.io>"]
description = "Zipkin exporter for OpenTelemetry"
homepage = "https://github.com/open-telemetry/opentelemetry-rust/tree/master/opentelemetry-zipkin"
repository = "https://github.com/open-telemetry/opentelemetry-rust/tree/master/opentelemetry-zipkin"
readme = "README.md"
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
    "asynchronous",
]
keywords = ["opentelemetry", "zipkin", "tracing", "async"]
license = "Apache-2.0"
edition = "2018"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["reqwest-blocking-client"]
reqwest-blocking-client = ["reqwest/blocking", "opentelemetry/reqwest"]
reqwest-client = ["opentelemetry/reqwest"]
surf-client = ["opentelemetry/surf"]

[dependencies]
async-trait = "0.1"
opentelemetry = { version = "0.9.0", path = "..", features = ["trace", "http"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
typed-builder = "0.7"
lazy_static = "1.4.0"
http = "0.2"
reqwest = { version = "0.10", optional = true }
surf = { version = "2.0", optional = true }

[dev-dependencies]
isahc = "=0.9.6"
