[package]
name = "actix-example"
version = "0.1.0"
edition = "2018"

[dependencies]
opentelemetry = { path = "../../", version = "0.1.5" }
opentelemetry-jaeger = { path = "../../opentelemetry-jaeger", version = "0.1.0" }
thrift = "0.13.0"

futures = "0.1.25"
actix-web = "1.0.9"
actix-service = "0.4.1"
