[package]
name = "opentelemetry-http"
version = "0.1.0"
authors = ["OpenTelemetry Authors <cncf-opentelemetry-contributors@lists.cncf.io>"]
description = "Helper implementations for exchange of traces and metrics over HTTP"
homepage = "https://github.com/open-telemetry/opentelemetry-rust"
repository = "https://github.com/open-telemetry/opentelemetry-rust"
keywords = ["opentelemetry", "tracing", "metrics"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
async-trait = "0.1.42"
http = "0.2.2"
isahc = { version = "0.9", default-features = false, optional = true }
opentelemetry = { version = "0.11.2", path = "../opentelemetry", features = ["trace"] }
reqwest = { version = "0.11", default-features = false, features = ["blocking"], optional = true }
surf = { version = "2.0", default-features = false, optional = true }
thiserror = "1"
