[package]
name = "basic-otlp"
version = "0.1.0"
edition = "2018"

[dependencies]
futures = "0.3"
lazy_static = "1.4"
opentelemetry = { path = "../../opentelemetry", features = ["tokio", "metrics", "serialize"] }
opentelemetry-otlp = { path = "../../opentelemetry-otlp" }
serde_json = "1.0"
tokio = { version = "0.2", features = ["full"] }
