[package]
name = "opentelemetry-appender-log"
version = "0.1.0"
edition = "2021"
description = "An OpenTelemetry appender for the log crate"
homepage = "https://github.com/open-telemetry/opentelemetry-rust/tree/main/opentelemetry-appender-log"
repository = "https://github.com/open-telemetry/opentelemetry-rust/tree/main/opentelemetry-appender-log"
readme = "README.md"
keywords = ["opentelemetry", "log", "logs"]
license = "Apache-2.0"
rust-version = "1.60"

[dependencies]
opentelemetry_api = { version = "0.19", path = "../opentelemetry-api", features = ["logs"]}
opentelemetry_sdk = { version = "0.19", path = "../opentelemetry-sdk", features = ["logs"]}
log = {version = "0.4.17", features = ["kv_unstable", "std"]}

