[package]
name = "external-otlp-tonic-tokio"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
env_logger = "0.9.0"
opentelemetry = {path = "../../opentelemetry", features = ["rt-tokio", "metrics"]}
opentelemetry-otlp = {path = "../../opentelemetry-otlp", features = ["tonic", "tls", "tls-roots"]}
serde_json = "1.0"
tokio = {version = "1.0", features = ["full"]}
tonic = {version = "0.8.0", default-features = false, features = ["tls"]}
url = "2.2.0"
