[package]
name = "metrics-advanced"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
rust-version.workspace = true
publish = false
autobenches = false

[[bin]]
name = "metrics-advanced"
path = "src/main.rs"
bench = false

[dependencies]
opentelemetry = { workspace = true, features = ["metrics"] }
opentelemetry_sdk = { workspace = true, features = ["metrics"] }
opentelemetry-stdout = { workspace = true, features = ["metrics"] }
tokio = { workspace = true, features = ["full"] }
