[package]
name = "external-otlp-grpcio-async-std"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-std = { version = "= 1.10.0", features = ["attributes"] }
env_logger = "0.9.0"
opentelemetry = { path = "../../../opentelemetry", features = ["rt-async-std"] }
opentelemetry-otlp = { path = "../../../opentelemetry-otlp", features = [
    "grpc-sys",
    "trace",
    "openssl-vendored"
], default-features = false }
serde_json = "1.0"
url = "2.2.0"
